# -*- coding: utf-8 -*-
"""YOLOv10_Screening_of_Fresh_and_Rotten.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CUFJzztTiad1bWVGgWgEia6UYprN4EsI
"""

!nvidia-smi

!rm -R "/content/sample_data" #exclui a pasta sample_data que o colab mostra padrão

!wget -P -q https://github.com/jameslahm/yolov10/releases/download/v1.0/yolov10n.pt

!pip install -q git+https://github.com/THU-MIG/yolov10.git

# Baixa o dataset do github
!git clone https://github.com/lsmgoes/Screening_of_Fresh_and_Rotten.git

!yolo task=detect mode=train epochs=30 batch=32 plots=True \
model='/content/-q/yolov10n.pt' \
data='/content/Screening_of_Fresh_and_Rotten/data.yaml'

# PARA BAIXAR A PASTA COM OS GRÁFICOS
import shutil
from google.colab import files

# Compactar a pasta (substitua 'runs' pelo nome da sua pasta)
shutil.make_archive('metrics', 'zip', '/content/runs/detect/train')

# Baixar o arquivo compactado
files.download('metrics.zip')

# from ultralytics import YOLOv10

# model_path = '/content/runs/detect/train/weights/best.pt'
# model = YOLOv10(model_path)
# results = model(source='/content/Screening_of_Fresh_and_Rotten/data/val/images/', conf=0.10,save=True)

# import glob
# import matplotlib.pyplot as plt
# import matplotlib.image as mpimg

# images = glob.glob('/content/runs/detect/predict/*.jpg')

# images_to_display = images[10:30]

# fig, axes = plt.subplots(2, 5, figsize=(20, 10))

# for i, ax in enumerate(axes.flat):
#     if i < len(images_to_display):
#         img = mpimg.imread(images_to_display[i])
#         ax.imshow(img)
#         ax.axis('off')
#     else:
#         ax.axis('off')

# plt.tight_layout()
# plt.show()

